# Generated by Django 5.2.4 on 2025-07-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
