# Generated by Django 5.2.4 on 2025-07-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_progress_book_alter_progress_percent_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='percent_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
